name: Run Trading Bot

on:
  schedule:
    - cron: "30 14 * * 1-5"  # 2:30 PM UTC = 7:00 PM IST, Mon-Fri
  workflow_dispatch: # Allows manual run
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run trading bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SYMBOL: ${{ secrets.SYMBOL }}   # optional; can set symbol in repo secret or default in code
        run: python trading_bot.py
