name: Run Trading Bot

on:
  schedule:
    - cron: "0 3 * * *"    # Daily at 03:00 UTC (≈ 8:30 AM IST)
  workflow_dispatch:       # Allow manual run from Actions UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run trading bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SYMBOL: ${{ secrets.SYMBOL }}   # optional; can set symbol in repo secret or default in code
        run: python trading_bot.py
